In [ ]:
import numpy as np

In [ ]:
arr = [0,1,2,3,4]
arr1 = np.array(arr)

In [ ]:
arr1.shape

(5,)

In [ ]:
arr1.reshape(5,1)

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [ ]:
arr1[4]

np.int64(4)

In [ ]:
arr3 = [[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]
arrr = np.array(arr3)

In [ ]:
arrr.shape

(3, 5)

In [ ]:
arrr[:,:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [ ]:
arrr[1:,0:2]

array([[ 6,  7],
       [11, 12]])

In [ ]:
arr = np.arange(10)

In [ ]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr[3:] = 100

In [ ]:
arr

array([  0,   1,   2, 100, 100, 100, 100, 100, 100, 100])

In [ ]:
val = 1
arr*2

array([  0,   2,   4, 200, 200, 200, 200, 200, 200, 200])

In [ ]:
np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
np.ones(4).reshape(2,2)

array([[1., 1.],
       [1., 1.]])

In [ ]:
np.random.randn(5,3)

array([[ 0.28946447,  1.00721902,  1.95729891],
       [-1.38934276,  0.41475104, -0.02947075],
       [-0.55160066,  0.61760884,  0.17767204],
       [ 0.93517387, -0.0683239 , -0.00380291],
       [ 0.01515102,  0.00804899, -0.57452213]])

In [ ]:
arr1 = np.random.randint(0,5)
arr1

0

In [ ]:
arr1 = np.random.randint(0,100,4)
#select 4 numbers
arr1

array([26, 47, 29, 37])

In [ ]:
np.random.random_sample(5)

array([0.17345529, 0.174159  , 0.53407252, 0.61547924, 0.55130061])